//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdventOfCode {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AdventOfCode.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100838
        ///70586
        ///129092
        ///133687
        ///51902
        ///91959
        ///73695
        ///71153
        ///50852
        ///145099
        ///57991
        ///55193
        ///97743
        ///103917
        ///74780
        ///113182
        ///83240
        ///88356
        ///70842
        ///144241
        ///100991
        ///90785
        ///112136
        ///89888
        ///136043
        ///133453
        ///59090
        ///109367
        ///111573
        ///135955
        ///133316
        ///53477
        ///89519
        ///51718
        ///107878
        ///58592
        ///147245
        ///60447
        ///79962
        ///51147
        ///147450
        ///143355
        ///130754
        ///148938
        ///95062
        ///85690
        ///56427
        ///120009
        ///128688
        ///138762
        ///75391
        ///52662
        ///128880
        ///75215
        ///109784
        ///55228
        ///77516
        ///107163
        ///78238
        ///134656
        ///66162
        ///128898
        ///67369
        ///56016
        ///103459
        ///142756
        ///111404
        ///106646
        ///972 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Day01Puzzle01 {
            get {
                return ResourceManager.GetString("Day01Puzzle01", resourceCulture);
            }
        }
    }
}
